language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ramezwasfy91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramezwasfy91/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-297017520260"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
